# Generated by Django 4.0.5 on 2022-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubecmd', '0002_alter_systemapplication_build_instruction_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemapplication',
            name='config_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
