# Generated by Django 4.0.5 on 2022-11-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubecmd', '0003_alter_systemapplication_config_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemapplication',
            old_name='config_json',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='systemapplicationinqueue',
            old_name='instruction_text',
            new_name='logs',
        ),
        migrations.RemoveField(
            model_name='systemapplication',
            name='config_text',
        ),
    ]
