# Generated by Django 4.0.5 on 2022-10-04 19:01

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=common.models.tz_now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_login_type', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Google')])),
                ('social_login_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'social_login_type')},
            },
        ),
    ]
