# Generated by Django 4.0.5 on 2022-11-15 20:11

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=common.models.tz_now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('subhostname', models.CharField(max_length=30, unique=True)),
                ('service', models.JSONField(null=True)),
                ('ingress', models.JSONField(null=True)),
                ('deployment', models.JSONField(null=True)),
                ('replicas', models.PositiveSmallIntegerField(default=1, null=True)),
                ('storage', models.PositiveSmallIntegerField(null=True)),
                ('cpu', models.PositiveSmallIntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
