# Generated by Django 4.0.5 on 2022-06-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_equity_group_alter_equity_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[('A', 1), ('B', 2), ('IP', 3), ('M', 4), ('P', 6), ('R', 7), ('T', 8), ('X', 9), ('XT', 10), ('Z', 11), ('ZP', 12)]),
        ),
    ]
