# Generated by Django 4.0.5 on 2022-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_equity_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('IN_ACTIVE', 1), ('ACTIVE', 2), ('SUSPENDED', 3), ('DELISTED', 4)]),
        ),
    ]
